### ISSUE TITLE
How can you read pixel?

### ISSUE THREAD

**Issue by pavunato** [Migdalo/writeups#1]
I got stuck in this problem when i extracted png has flag tag but i don't know what to do next.
How can you know read the pixel values. I mean this piece of code

```
                if b != 255:
                    plain += chr(r)
                    plain += chr(g)
                else:
                    return plain
```

Can you explain it for me? 
Thanks!

**Comment by Migdalo** [comment]
The pixel RBG values are read with [getpixel(xy) function](http://pillow.readthedocs.io/en/3.4.x/reference/Image.html#PIL.Image.Image.getpixel). The function is part of PIL, and it returns the RBG value of a pixel in the given coordinates as a tuple.

In this task, it's worth noticing that the part of the image that includes the hidden information has black background, whereas the rest of the image has white background. If you print out all the pixel values until the first white pixel, you'll notice that during the encoding part b only gets the value of 0. After the encoding, it only gets the value of 255. This is why I'm using the value of b to know when the encoding ends (if b != 255).

Finding out which values to print was a matter of trial and error. At first I tried printing just the values of r. This resulted in something that reminded a file, but seemed to lack some characters. Second step was to print out  both r and g values. The result of this was a working ELF file and the flag. 

I hope this answered to your question.
